name: yuninet_app
description: A modern social platform app for youth connection and empowerment.
publish_to: "none" # App won't be published to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ---------------- UI & Design ----------------
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.8
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9            # ✅ SVG icons support
  lottie: ^2.7.0                 # ✅ Animations (typing, reactions, etc.)

  # ---------------- Media & Image Handling ----------------
  video_player: ^2.9.1
  chewie: ^1.7.1
  photo_view: ^0.14.0
  file_picker: ^6.2.0
  image_picker: ^1.0.7
  open_filex: ^4.0.2             # ✅ Open files (PDF, docs, media)

  # ---------------- Linking & Sharing ----------------
  url_launcher: ^6.2.6
  share_plus: ^11.0.0

  # ---------------- Backend & APIs ----------------
  supabase_flutter: ^2.7.0       # ✅ Backend, DB, auth, real-time
  http: ^1.2.1
  uuid: ^4.2.2
  mime: ^1.0.4
  cloud_firestore: ^5.6.12       # ✅ Optional (extra realtime DB if needed)

  # ---------------- State Management ----------------
  provider: ^6.1.2
  get: ^4.6.6                    # ✅ Lightweight state management/navigation

  # ---------------- AI & Environment ----------------
  flutter_dotenv: ^5.1.0
  google_generative_ai: ^0.4.3   # ✅ Gemini official SDK

  # ---------------- Storage & Local Database ----------------
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0 # ✅ For secure key storage (E2E encryption)

  # ---------------- Notifications ----------------
  flutter_local_notifications: ^12.0.4

  # ---------------- Date & Time ----------------
  intl: ^0.19.0

  # ---------------- Download & Save Files ----------------
  dio: ^5.4.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  image_gallery_saver: ^2.0.3    # ✅ Save media locally

  # ---------------- Chat Specific ----------------
  encrypt: ^5.0.3                # ✅ End-to-end encryption
  flutter_webrtc: ^0.9.33        # ✅ Voice/Video calls
  emoji_picker_flutter: ^1.6.3   # ✅ Emoji keyboard like WhatsApp/Telegram

  # ---------------- Icons ----------------
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/icons/icon.png
    - assets/images/default_user.png
    # ⚠️ Do not include .env here, keep it in project root (not assets).

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "assets/icons/icon.png"
  adaptive_icon_foreground: "assets/icons/icon.png"